openapi: 3.0.3
info:
  title: API de Búsqueda y Navegación de Parroquias y Capillas
  version: 1.0.0

tags:
  - name: Búsqueda Pública (Church)
    description: Endpoints para la búsqueda, listado y detalle de Parroquias y Capillas.

paths:
  # ====================================================================
  # 1. BÚSQUEDA INICIAL Y LISTADO PARA MAPA/COMBO BOX (PAGINADO)
  # ====================================================================
  /api/public/church/search:
    post:
      tags:
        - Búsqueda Pública (Church)
      summary: Buscar Parroquias y Capillas por nombre, o listar todas.
      description: "Usado por la barra de búsqueda y el mapa. Devuelve todas las ubicaciones coincidentes. No requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - page
                - limit
              properties:
                query:
                  type: string
                  description: "Texto para buscar por nombre de parroquia o capilla. Si está vacío, lista todo."
                  example: string
                page:
                  type: integer
                  example: 1
                limit:
                  type: integer
                  example: 10
      responses:
        "200":
          description: Resultados de búsqueda para el mapa y la lista lateral (Combo Box).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID de la ubicación.
                          example: 5
                        name:
                          type: string
                          description: Nombre.
                          example: string
                        address:
                          type: string
                          description: Dirección.
                          example: string
                        type:
                          type: string
                          enum: [PARROQUIA, CAPILLA]
                          description: "Tipo de ubicación."
                          example: PARROQUIA
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 35

  # ====================================================================
  # 2. SELECCIÓN DE PARROQUIA DEL COMBO BOX (Listado de Tarjetas)
  # ====================================================================
  /api/public/church/select-parish:
    post:
      tags:
        - Búsqueda Pública (Church)
      summary: Obtener el detalle de la Parroquia seleccionada y su lista de Capillas (Para tarjetas).
      description: "Usado al seleccionar un ítem del combo box. Devuelve la Parroquia y sus Capillas anidadas con la información mínima para las tarjetas de resultados. No requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - parish_id
              properties:
                parish_id:
                  type: integer
                  description: ID de la Parroquia seleccionada.
                  example: 15

      responses:
        "200":
          description: Parroquia seleccionada y Capillas anidadas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      selected_parish:
                        type: object
                        description: Tarjeta principal de la Parroquia.
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                            example: string
                          address:
                            type: string
                            example: string
                          type:
                            type: string
                            example: PARROQUIA
                      chapels:
                        type: array
                        description: Lista de tarjetas de las capillas anexas.
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                              example: string
                            address:
                              type: string
                              example: string
                            type:
                              type: string
                              example: CAPILLA
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # 3. DETALLE DE MODAL (Modal que aparece al hacer clic en la tarjeta)
  #    RUTA AJUSTADA A /api/public/church/{chapel_id}/info
  # ====================================================================
  /api/public/church/{chapel_id}/info:
    parameters:
      - name: chapel_id
        in: path
        required: true
        schema:
          type: integer
        description: ID de la Capilla seleccionada (o ID de la Capilla principal si se seleccionó una Parroquia).
    get:
      tags:
        - Búsqueda Pública (Church)
      summary: Obtener el detalle del Modal de Información (Perfil y Contacto).
      description: "Devuelve todos los datos visibles en el modal (Teléfono, Encargado/Párroco, Descripción). La respuesta se genera desde la Capilla (tabla chapel). No requiere JWT."
      responses:
        "200":
          description: Perfil detallado obtenido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: string
                      type:
                        type: string
                        enum: [Parroquia, Capilla]
                        example: Parroquia
                      address:
                        type: string
                        example: string
                      phone:
                        type: string
                        example: string
                      description:
                        type: string
                        example: string
                      parroco:
                        type: string
                        nullable: true
                        description: 'Nombre del Párroco (Solo si type es "Parroquia", mapeado desde la Capilla Principal).'
                        example: string
                      encargado:
                        type: string
                        nullable: true
                        description: 'Nombre del Encargado (Solo si type es "Capilla", mapeado desde la Capilla.phone o campo similar).'
                        example: string
                      parroquia_padre_name:
                        type: string
                        nullable: true
                        description: 'Nombre de la Parroquia Padre (Solo si type es "Capilla").'
                        example: string
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # 4. ACTOS LITÚRGICOS (Lista Fija - GET sin META)
  #    RUTA AJUSTADA A /api/public/church/{chapel_id}/acts
  # ====================================================================
  /api/public/church/{chapel_id}/acts:
    get:
      tags:
        - Búsqueda Pública (Church)
      summary: Listar los Actos Litúrgicos disponibles para la ubicación (Lista completa).
      description: "Devuelve una lista COMPLETA y no paginada de los tipos de actos litúrgicos disponibles (solo Nombre). No requiere JWT."
      parameters:
        - name: chapel_id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la Capilla seleccionada.
      responses:
        "200":
          description: Lista de actos disponibles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                          example: string
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
  # ====================================================================
  # 5. PERFIL PÚBLICO DETALLADO (Botón 'Ver Perfil')
  #    Función: Pantalla completa con info extendida, fotos y variantes de eventos.
  # ====================================================================
  /api/public/church/{chapel_id}/profile:
    parameters:
      - name: chapel_id
        in: path
        required: true
        schema:
          type: integer
        description: ID de la Capilla seleccionada.
    get:
      tags:
        - Búsqueda Pública (Church)
      summary: Obtener el perfil público detallado y las variantes de eventos disponibles.
      description: "Usado por el botón 'Ver perfil'. Devuelve información de contacto, fotos, estado y la lista completa de eventos/variantes disponibles para reserva. No requiere JWT."
      responses:
        "200":
          description: Perfil detallado y eventos disponibles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      # --- Encabezado y Fotos ---
                      parish_name:
                        type: string
                        description: Nombre de la Parroquia Padre.
                        example: string
                      chapel_name:
                        type: string
                        description: Nombre de la Capilla.
                        example: string
                      cover_photo:
                        type: string
                        description: URL/Path de la imagen de fondo (Portada).
                        example: string
                      profile_photo:
                        type: string
                        description: URL/Path de la imagen de perfil (Pequeña).
                        example: string
                      primary_color:
                        type: string
                        description: Color primario de la Parroquia (formato hexadecimal).
                        example: "#4A90E2"
                      secondary_color:
                        type: string
                        description: Color secundario de la Parroquia (formato hexadecimal).
                        example: "#2C5F8D"
                      # --- Información de Contacto (Lado Izquierdo) ---
                      address:
                        type: string
                        description: Dirección.
                        example: string
                      email:
                        type: string
                        description: Correo.
                        example: string
                      phone:
                        type: string
                        description: Teléfono.
                        example: string
                      coordinates:
                        type: string
                        description: Coordenadas.
                        example: string
                      active:
                        type: boolean
                        description: Estado (Activa/Inactiva).
                        example: true
                      # --- Eventos Disponibles (Lado Derecho) ---
                      events:
                        type: array
                        description: Lista de variantes de eventos disponibles para reserva.
                        items:
                          type: object
                          properties:
                            event_variant_id:
                              type: integer
                              description: ID de la variante específica.
                            event_name:
                              type: string
                              description: Nombre del Evento (ej. Matrimonio).
                              example: string
                            variant_name:
                              type: string
                              description: Nombre de la variante (ej. Matrimonio Privado).
                              example: string
                            variant_type:
                              type: string
                              enum: [Privado, Comunitario]
                              description: Tipo de evento.
                              example: Privado
                            variant_description:
                              type: string
                              description: Descripción de la variante.
                              example: string
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
