openapi: 3.0.3
info:
  title: API de Gestión de Parroquia (Cuenta y Capillas)
  version: 1.0.0
tags:
  - name: Cuenta de Parroquia
    description: Endpoints para gestionar el perfil y credenciales de la parroquia autenticada.
  - name: Gestión de Capillas
    description: Endpoints para el CRUD y listado administrativo de Capillas de la parroquia.

paths:
  # ====================================================================
  # I. CUENTA DE PARROQUIA (Perfil y Credenciales del Administrador)
  #    *Los campos coordinates y email solo existían en Capillas, no se afectan aquí.*
  # ====================================================================
  /api/parish/account:
    get:
      tags:
        - Cuenta de Parroquia
      summary: Obtener toda la información de la cuenta de la parroquia (Info y Credenciales).
      description: "Permiso requerido: R_PARROQUIA_INFO (35) y Leer Perfil Propio (Implícito). Requiere JWT."
      responses:
        '200':
          description: Éxito. Todos los datos de la cuenta obtenidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Nombres de Parroquia.
                        example: Parroquia Nuestra Señora de la Consolación
                      address:
                        type: string
                        description: Dirección.
                        example: Algarrobos 222, Chiclayo
                      coordinates:
                        type: string
                        description: Coordenadas.
                        example: -6.781771909,-79.84091136
                      phone:
                        type: string
                        description: Celular.
                        example: 999888777
                      primary_color:
                        type: string
                        description: Color primario.
                        example: '#DC2626'
                      secondary_color:
                        type: string
                        description: Color secundario.
                        example: '#2563EB'
                      profile_photo:
                        type: string
                        description: Foto perfil.
                        example: iglesia.jpg
                      cover_photo:
                        type: string
                        description: Foto portada.
                        example: iglesia_portada.jpg
                      username:
                        type: string
                        description: Usuario del administrador.
                        example: parroquia_conso_admin
                      email:
                        type: string
                        description: Correo del administrador.
                        example: correo@parroquia.com
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/parish/account/info:
    patch:
      tags:
        - Cuenta de Parroquia
      summary: Actualizar PARCIALMENTE la información de la parroquia (Datos visuales y de contacto).
      description: "Permiso requerido: U_PARROQUIA_INFO (36). Requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Parroquia Nuestra Señora de la Consolación MOD
                address:
                  type: string
                  example: Nueva Dirección 123
                coordinates:
                  type: string
                  example: -6.78,-79.84
                phone:
                  type: string
                  example: 999111222
                primary_color:
                  type: string
                  example: '#000000'
                secondary_color:
                  type: string
                  example: '#FFFFFF'
                profile_photo:
                  type: string
                  example: nueva_iglesia_perfil.jpg
                cover_photo:
                  type: string
                  example: nueva_iglesia_portada.jpg
      responses:
        '200':
          description: Éxito. Información de la parroquia actualizada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/parish/account/credentials:
    patch:
      tags:
        - Cuenta de Parroquia
      summary: Actualizar PARCIALMENTE el Usuario, Correo y/o Contraseña del administrador.
      description: "Permiso requerido: U_PARROQUIA_INFO (36) y Actualizar Perfil Propio (Implícito). Requiere JWT. Se requiere current_password para cualquier cambio."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: nuevo_conso_admin
                  description: Nuevo nombre de usuario.
                email:
                  type: string
                  example: nuevo.correo@parroquia.com
                  description: Nuevo correo.
                new_password:
                  type: string
                  nullable: true
                  description: Nueva contraseña.
                  example: NuevaContra456
                confirm_new_password:
                  type: string
                  nullable: true
                  description: Confirmación de nueva contraseña.
                  example: NuevaContra456
                current_password:
                  type: string
                  description: Contraseña actual (requerida para seguridad).
                  example: ContraseñaActual123
              required:
                - username
                - email
                - current_password
      responses:
        '200':
          description: Éxito. Credenciales actualizadas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # II. GESTIÓN DE CAPILLAS (CRUD de capillas de la Parroquia)
  #     *Se eliminan los campos 'coordinates' y 'email' de todas las APIs.*
  # ====================================================================
  /api/parish/chapels/create:
    post:
      tags:
        - Gestión de Capillas
      summary: Crear una nueva Capilla para la Parroquia autenticada.
      description: "Permiso requerido: C_PARROQUIA_CAPILLA (39). Requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre de la Capilla.
                  example: Capilla San Judas Tadeo
                address:
                  type: string
                  description: Dirección.
                  example: Av. Principal 101
                phone:
                  type: string
                  description: Teléfono/Celular.
                  example: 999111222
                profile_photo:
                  type: string
                  description: Foto de perfil.
                  example: capilla_perfil.jpg
                cover_photo:
                  type: string
                  description: Foto de portada.
                  example: capilla_portada.jpg
              required:
                - name
                - address
                - phone
      responses:
        '200':
          description: Capilla creada exitosamente.

  /api/parish/chapels/search:
    post:
      tags:
        - Gestión de Capillas
      summary: Listar Capillas de la Parroquia con paginación y búsqueda.
      description: "Muestra ID, Nombre y Dirección. Permiso requerido: R_PARROQUIA_CAPILLA (41). Requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - page
                - limit
              properties:
                query:
                  type: string
                  description: Texto para buscar por nombre o dirección.
                  example: "Capilla 1"
                page:
                  type: integer
                  example: 1
                limit:
                  type: integer
                  example: 10
      responses:
        '200':
          description: Lista paginada de capillas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          description: Nombre de la Capilla.
                          example: Capilla San Judas Tadeo
                        address:
                          type: string
                          description: Dirección de la Capilla.
                          example: Dirección de la Capilla 1
                        active:
                          type: boolean
                          description: Estado de la Capilla.
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 50

  /api/parish/chapels/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
        description: ID de la Capilla.
    get:
      tags:
        - Gestión de Capillas
      summary: Obtener detalle de una Capilla (Ver).
      description: "Devuelve toda la información. Permiso requerido: R_PARROQUIA_CAPILLA (41). Requiere JWT."
      responses:
        '200':
          description: Detalle de la Capilla obtenido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        description: Nombre de la Capilla.
                        example: Capilla San Judas Tadeo
                      address:
                        type: string
                        description: Dirección de la Capilla.
                        example: Dirección de la Capilla 1
                      phone:
                        type: string
                        description: Teléfono/Celular.
                        example: 999111222
                      profile_photo:
                        type: string
                        description: Foto de perfil.
                        example: capilla_perfil.jpg
                      cover_photo:
                        type: string
                        description: Foto de portada.
                        example: capilla_portada.jpg
                      active:
                        type: boolean
                        description: Estado.
                        example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
        '404':
          description: Capilla no encontrada.
    
    patch:
      tags:
        - Gestión de Capillas
      summary: Actualizar PARCIALMENTE los datos de una Capilla (Editar).
      description: "Permiso requerido: U_PARROQUIA_CAPILLA (42). Requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Capilla San Judas Tadeo MOD
                address:
                  type: string
                  example: Nueva Dirección MOD
                phone:
                  type: string
                  example: 999111222
                profile_photo:
                  type: string
                  example: nueva_foto_perfil.jpg
                cover_photo:
                  type: string
                  example: nueva_foto_portada.jpg
      responses:
        '200':
          description: Capilla actualizada exitosamente.
        '404':
          description: Capilla no encontrada.

  /api/parish/chapels/{id}/status:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
        description: ID de la Capilla.
    patch:
      tags:
        - Gestión de Capillas
      summary: Cambiar el estado (activar/desactivar) de una Capilla.
      description: "Utilizado por el switch de Estado. Permiso requerido: U_ESTADO_CAPILLA (40). Requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - active
              properties:
                active:
                  type: boolean
                  description: Nuevo estado de la Capilla.
                  example: false
      responses:
        '200':
          description: Estado de la Capilla actualizado.
        '404':
          description: Capilla no encontrada.

  # ====================================================================
  # III. ELIMINACIÓN DE CAPILLA (RUTA Y FORMATO SOLICITADO)
  #      Ruta: /api/diocese/chapels/{id}/delete
  # ====================================================================
  /api/diocese/chapels/{id}/delete:
    delete:
      tags:
        - Gestión de Capillas
      summary: Eliminar físicamente una Capilla por ID.
      description: "Permiso requerido: D_PARROQUIA_CAPILLA (43). Requiere JWT. (Usando la ruta de Diócesis)."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID de la capilla.
      responses:
        '200':
          description: Éxito. Capilla eliminada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""