openapi: 3.0.0
info:
  title: Parroquia - Reports API
  version: 1.0.0
  description: |
    API para reportes del módulo de Parroquia.
    
    Todas las rutas requieren autenticación mediante cookie (session_token).

tags:
  - name: Reports - Parroquia
    description: Endpoints para reportes de parroquia

paths:
  /api/reports/events-by-chapel:
    get:
      tags:
        - Reports - Parroquia
      summary: Obtener eventos realizados por capilla
      description: |
        Devuelve la cantidad de reservas completadas agrupadas por tipo de evento para una capilla específica.
        Utilizado en el reporte RP05 - Gráfico 1: Eventos generales realizados.
      security:
        - cookieAuth: []
      parameters:
        - name: chapel_name
          in: query
          description: Nombre de la capilla
          required: true
          schema:
            type: string
            example: Capilla San Francisco
      responses:
        '200':
          description: Datos de eventos obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsByChapelResponse'
        '400':
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Capilla no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_token
      description: Token de sesión JWT almacenado en una cookie HttpOnly.

  responses:
    Unauthorized:
      description: No autorizado. El token de sesión falta, es inválido o ha expirado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    BaseResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje descriptivo para la operación
          example: Operación exitosa

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error general
          example: Ocurrió un error
        error:
          type: string
          description: Detalles específicos del error
          example: Parámetro chapel_name es requerido

    EventCount:
      type: object
      properties:
        event_name:
          type: string
          example: Bautismo
        count:
          type: integer
          example: 23

    EventsByChapelResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                chapel_name:
                  type: string
                  example: Capilla San Francisco
                events:
                  type: array
                  items:
                    $ref: '#/components/schemas/EventCount'
