openapi: 3.0.3
info:
  title: API de Búsqueda y Navegación de Parroquias y Capillas
  version: 1.0.0

tags:
  - name: Búsqueda Pública (Church)
    description: Endpoints para la búsqueda, listado y detalle de Parroquias y Capillas.

paths:
  # ====================================================================
  # 1. BÚSQUEDA INICIAL Y LISTADO PARA MAPA/COMBO BOX (PAGINADO)
  # ====================================================================
  /api/public/church/search:
    post:
      tags:
        - Búsqueda Pública (Church)
      summary: Buscar Parroquias y Capillas por nombre, o listar todas.
      description: "Usado por la barra de búsqueda y el mapa. Devuelve todas las ubicaciones coincidentes. No requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: "Texto para buscar por nombre de parroquia o capilla. Si está vacío, lista todo."
                  example: string
      responses:
        "200":
          description: Resultados de búsqueda para el mapa y la lista lateral (Combo Box).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID de la ubicación.
                          example: 5
                        name:
                          type: string
                          description: Nombre.
                          example: string
                        address:
                          type: string
                          description: Dirección.
                          example: string
                        type:
                          type: string
                          enum: [PARROQUIA, CAPILLA]
                          description: "Tipo de ubicación."
                          example: PARROQUIA
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # 2. SELECCIÓN DE UBICACIÓN (PARROQUIA O CAPILLA) DEL COMBO BOX (Listado de Tarjetas)
  # ====================================================================
  /api/public/church/select-location:
    post:
      tags:
        - Búsqueda Pública (Church)
      summary: Obtener tarjetas de ubicación(es) según tipo seleccionado.
      description: |
        Maneja dos casos según el tipo recibido:
        - **Si type=PARROQUIA**: Busca la capilla base (chapel_base=true) con el parish_id y devuelve su info + todas las capillas asociadas (chapel_base=false) del mismo parish_id.
        - **Si type=CAPILLA**: Busca la capilla con el chapel_id y devuelve solo su información.
        
        Cada tarjeta contiene 4 campos: id, name, address, type.
        No requiere JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location_id
                - type
              properties:
                location_id:
                  type: integer
                  description: "Si type=PARROQUIA → parish_id. Si type=CAPILLA → chapel_id."
                  example: 15
                type:
                  type: string
                  enum: [PARROQUIA, CAPILLA]
                  description: "Tipo de ubicación a consultar."
                  example: PARROQUIA

      responses:
        "200":
          description: Tarjetas de ubicación(es) según el tipo solicitado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: [PARROQUIA, CAPILLA]
                        description: "Tipo de consulta realizada."
                        example: PARROQUIA
                      selected_location:
                        type: object
                        description: "Tarjeta principal. Si type=PARROQUIA es la chapel_base, si type=CAPILLA es la capilla consultada."
                        properties:
                          id:
                            type: integer
                            description: "ID de la Chapel."
                            example: 15
                          name:
                            type: string
                            description: "Nombre."
                            example: "Santa María Catedral"
                          address:
                            type: string
                            description: "Dirección."
                            example: "Plaza de Armas, Chiclayo"
                          type:
                            type: string
                            enum: [PARROQUIA, CAPILLA]
                            description: "PARROQUIA si chapel_base=true, CAPILLA si chapel_base=false."
                            example: PARROQUIA
                      chapels:
                        type: array
                        description: "Lista de capillas asociadas. Solo se llena si type=PARROQUIA (incluye todas las chapel con chapel_base=false del mismo parish_id). Si type=CAPILLA, este array estará vacío."
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: "ID de la Chapel."
                              example: 101
                            name:
                              type: string
                              description: "Nombre de la Capilla."
                              example: "Capilla San Francisco"
                            address:
                              type: string
                              description: "Dirección."
                              example: "Calle San José 145, Chiclayo"
                            type:
                              type: string
                              description: "Siempre CAPILLA."
                              example: CAPILLA
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # 3. DETALLE DE MODAL (Modal que aparece al hacer clic en la tarjeta)
  #    RUTA AJUSTADA A /api/public/church/info
  # ====================================================================
  /api/public/church/info:
    post:
      tags:
        - Búsqueda Pública (Church)
      summary: Obtener el detalle completo de una ubicación (Parroquia o Capilla).
      description: "Devuelve todos los datos visibles en el modal (Teléfono, Encargado/Párroco, Descripción). Si es Parroquia, devuelve también la lista de IDs de capillas asociadas. No requiere JWT."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location_id
                - type
              properties:
                location_id:
                  type: integer
                  description: "ID de la ubicación. Si type=PARROQUIA, es el parish_id. Si type=CAPILLA, es el chapel_id."
                  example: 15
                type:
                  type: string
                  enum: [PARROQUIA, CAPILLA]
                  description: Tipo de ubicación.
                  example: PARROQUIA
      responses:
        "200":
          description: Información detallada de la ubicación obtenida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        description: "Nombre de la Chapel."
                        example: string
                      type:
                        type: string
                        enum: [PARROQUIA, CAPILLA]
                        description: "PARROQUIA si chapel_base=true, CAPILLA si chapel_base=false."
                        example: PARROQUIA
                      address:
                        type: string
                        description: "Dirección de la Chapel."
                        example: string
                      phone:
                        type: string
                        description: "Teléfono de la Chapel."
                        example: string
                      email:
                        type: string
                        description: "Email de la Chapel."
                        example: string
                      parish_name:
                        type: string
                        nullable: true
                        description: 'Nombre de la Parroquia Padre (Solo si type es "CAPILLA").'
                        example: string
                      chapels:
                        type: array
                        nullable: true
                        description: 'Lista de capillas asociadas con su información completa (Solo si type es "PARROQUIA"). Incluye todas las chapel con mismo parish_id y chapel_base=false.'
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: "ID de la Capilla."
                              example: 4
                            name:
                              type: string
                              description: "Nombre de la Capilla."
                              example: "Capilla San Francisco"
                            address:
                              type: string
                              description: "Dirección de la Capilla."
                              example: "Calle San José 145, Chiclayo"
                            phone:
                              type: string
                              description: "Teléfono de la Capilla."
                              example: "(074) 123-457"
                            email:
                              type: string
                              description: "Email de la Capilla."
                              example: "capilla.sanfrancisco@gmail.com"
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # 4. ACTOS LITÚRGICOS (Lista Fija - GET sin META)
  #    RUTA AJUSTADA A /api/public/church/{chapel_id}/acts
  # ====================================================================
  /api/public/church/{chapel_id}/acts:
    get:
      tags:
        - Búsqueda Pública (Church)
      summary: Listar los Actos Litúrgicos disponibles para la ubicación (Lista completa).
      description: "Devuelve una lista COMPLETA y no paginada de los tipos de actos litúrgicos disponibles (solo Nombre). No requiere JWT."
      parameters:
        - name: chapel_id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la Capilla seleccionada.
      responses:
        "200":
          description: Lista de actos disponibles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                          example: string
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
  # ====================================================================
  # 5. PERFIL PÚBLICO DETALLADO (Botón 'Ver Perfil')
  #    Función: Pantalla completa con info extendida, fotos y variantes de eventos.
  # ====================================================================
  /api/public/church/{chapel_id}/profile:
    parameters:
      - name: chapel_id
        in: path
        required: true
        schema:
          type: integer
        description: ID de la Capilla seleccionada.
    get:
      tags:
        - Búsqueda Pública (Church)
      summary: Obtener el perfil público detallado y las variantes de eventos disponibles.
      description: "Usado por el botón 'Ver perfil'. Devuelve información de contacto, fotos, estado y la lista completa de eventos/variantes disponibles para reserva. No requiere JWT."
      responses:
        "200":
          description: Perfil detallado y eventos disponibles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      # --- Encabezado y Fotos ---
                      parish_name:
                        type: string
                        description: Nombre de la Parroquia Padre.
                        example: string
                      chapel_name:
                        type: string
                        description: Nombre de la Capilla.
                        example: string
                      cover_photo:
                        type: string
                        description: URL/Path de la imagen de fondo (Portada).
                        example: string
                      profile_photo:
                        type: string
                        description: URL/Path de la imagen de perfil (Pequeña).
                        example: string
                      primary_color:
                        type: string
                        description: Color primario de la Parroquia (formato hexadecimal).
                        example: "#4A90E2"
                      secondary_color:
                        type: string
                        description: Color secundario de la Parroquia (formato hexadecimal).
                        example: "#2C5F8D"
                      # --- Información de Contacto (Lado Izquierdo) ---
                      address:
                        type: string
                        description: Dirección.
                        example: string
                      email:
                        type: string
                        description: Correo.
                        example: string
                      phone:
                        type: string
                        description: Teléfono.
                        example: string
                      coordinates:
                        type: string
                        description: Coordenadas.
                        example: string
                      active:
                        type: boolean
                        description: Estado (Activa/Inactiva).
                        example: true
                      # --- Eventos Disponibles (Lado Derecho) ---
                      events:
                        type: array
                        description: Lista de variantes de eventos disponibles para reserva.
                        items:
                          type: object
                          properties:
                            event_variant_id:
                              type: integer
                              description: ID de la variante específica.
                            event_name:
                              type: string
                              description: Nombre del Evento (ej. Matrimonio).
                              example: string
                            variant_name:
                              type: string
                              description: Nombre de la variante (ej. Matrimonio Privado).
                              example: string
                            variant_type:
                              type: string
                              enum: [Privado, Comunitario]
                              description: Tipo de evento.
                              example: Privado
                            variant_description:
                              type: string
                              description: Descripción de la variante.
                              example: string
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
