openapi: 3.0.3
info:
  title: API Parroquia - Buscar Parroquia o Capilla (Map Search)
  description: |
    API para la gestión de la cuenta de la parroquia autenticada y sus capillas.

    Autenticación requerida: JWT (Cookie)

    Estructura de respuesta estándar:

    {
      "message": "Mensaje descriptivo de la operación",
      "data": {}, 
      "error": "",
      "traceback": "",
      "meta": {
        "total_records": 0
      }
    }
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Servidor de desarrollo

tags:
  - name: Search Parroquia/Capilla
    description: Endpoints para la búsqueda y selección en el mapa

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JWT

  schemas:
    MapSearchItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
          description: "parish | chapel"
        address:
          type: string
        email:
          type: string
          format: email
          nullable: true
        coordinates:
          type: string
          example: "-6.78177,-79.84091"
        phone:
          type: string
          nullable: true
        active:
          type: boolean
          example: true

    MapSearchListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MapSearchItem'
        meta:
          type: object
          properties:
            total_records:
              type: integer
              example: 0

    ParishProfile:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
          example: "parish"
        address:
          type: string
        phone:
          type: string
          nullable: true
        parish_priest:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        acts:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              schedule:
                type: string
              active:
                type: boolean

    ChapelProfile:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
          example: "chapel"
        address:
          type: string
        phone:
          type: string
          nullable: true
        caretaker:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        parent_parish:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        acts:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              schedule:
                type: string
              active:
                type: boolean

    BaseResponse:
      type: object
      properties:
        message:
          type: string
        data:
          oneOf:
            - type: object
            - type: array
        error:
          type: string
        traceback:
          type: string
    ChurchProfile:
      type: object
      description: Perfil unificado para parroquia o capilla
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: "Santa María Catedral"
        tipo:
          type: string
          description: "parroquia | capilla"
          example: "parroquia"
        latitud:
          type: number
          format: float
          example: -6.771611
        longitud:
          type: number
          format: float
          example: -79.837778
        coordinates:
          type: string
          example: "-6.771611,-79.837778"
        direccion:
          type: string
          example: "Plaza de Armas, Chiclayo"
        email:
          type: string
          format: email
          nullable: true
        telefono:
          type: string
          example: "(074) 123-456"
          nullable: true
        active:
          type: boolean
          example: true
        parroco:
          type: string
          example: "Padre José García"
          nullable: true
        descripcion:
          type: string
          example: "Catedral principal de la Diócesis de Chiclayo"
          nullable: true
        eventos:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              nombre:
                type: string
        chapels:
          type: array
          description: "Lista de capillas si el registro es una parroquia"
          items:
            type: object
            properties:
              id:
                type: integer
              nombre:
                type: string
              tipo:
                type: string
                example: "capilla"

    Variant:
      type: object
      properties:
        variant_id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        current_price:
          type: number
          format: float
        max_capacity:
          type: integer

    EventWithVariants:
      type: object
      properties:
        event_id:
          type: integer
        event_name:
          type: string
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'

security:
  - cookieAuth: []

paths:
  /api/parish/search:
    post:
      tags:
        - Search Parroquia/Capilla
      summary: Buscar parroquia o capilla por nombre
      description: |
        Busca por nombre tanto en parroquias como en capillas. Usado por la barra de búsqueda
        en la pantalla principal (mapa). Requiere `page` y `limit`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - page
                - limit
              properties:
                name_query:
                  type: string
                  description: "Texto para buscar por nombre de parroquia o capilla"
                page:
                  type: integer
                  example: 1
                limit:
                  type: integer
                  example: 10
      responses:
        "200":
          description: Resultados de búsqueda de parroquias/capillas
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/MapSearchListResponse'
        "400":
          description: Parámetros inválidos

  /api/church/list:
    post:
      tags:
        - Search Parroquia/Capilla
      summary: Obtener listado (combo) de parroquias y capillas (paged)
      description: |
        Devuelve un listado de parroquias y capillas (paginado). Entrada obligatoria: `page` y `limit`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - page
                - limit
              properties:
                page:
                  type: integer
                  example: 1
                limit:
                  type: integer
                  example: 10
      responses:
        "200":
          description: Lista paginada de parroquias y capillas
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          items:
                            type: array
                            items:
                              $ref: '#/components/schemas/ChurchProfile'
                          meta:
                            type: object
                            properties:
                              total_records:
                                type: integer
                                example: 0

  /api/church/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Search Parroquia/Capilla
      summary: Obtener detalle de parroquia o capilla seleccionada
      description: |
        Devuelve información detallada de la parroquia o capilla seleccionada (unificado).
        El campo `tipo` diferenciará si es `parroquia` o `capilla`.
      responses:
        "200":
          description: Detalle obtenido
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/ChurchProfile'
        "404":
          description: No encontrado

  # Eliminadas rutas específicas de capilla y profile-url para usar el endpoint unificado /api/church/{id}

  /api/acts/chapel/search:
    post:
      tags:
        - Search Parroquia/Capilla
      summary: Listar actos por capilla
      description: |
        Devuelve actos asociados a una capilla dada (uso principal para poblar la lista de eventos).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapel_id
                - page
              properties:
                chapel_id:
                  type: integer
                page:
                  type: integer
                  example: 1
      responses:
        "200":
          description: Lista de actos por capilla (id y nombre)
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          items:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                nombre:
                                  type: string

  /api/church-search/{chapel_id}/variants: # RUTA MODIFICADA A /api/church-search/
    parameters:
      - name: chapel_id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        required: false
        schema:
          type: integer
          example: 1
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          example: 10
    get:
      tags:
        - Search Parroquia/Capilla
      summary: Perfil y eventos de la capilla/parroquia seleccionada
      description: |
        Devuelve el perfil (nombre, dirección, correo, teléfono, coordenadas, estado) de la capilla o parroquia
        identificada por `chapel_id` y la lista de eventos asociados. Cada evento incluye nombre, tipo
        (privado|comunitario) y descripción.
      responses:
        "200":
          description: Perfil (sólo campos solicitados) y eventos (sólo nombre,tipo,descripcion)
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          perfil:
                            type: object
                            properties:
                              nombre:
                                type: string
                              direccion:
                                type: string
                              email:
                                type: string
                                format: email
                                nullable: true
                              telefono:
                                type: string
                                nullable: true
                              coordinates:
                                type: string
                                example: "-6.771611,-79.837778"
                          events:
                            type: object
                            properties:
                              items:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    nombre:
                                      type: string
                                    tipo:
                                      type: string
                                      description: "privado | comunitario"
                                    descripcion:
                                      type: string
                                      nullable: true
        "404":
          description: Capilla/Parroquia no encontrada

# Notas:
# - La UI principal (mapa) usará `/api/parish/search` para autocompletar y `/api/church/list` para listas paginadas.
# - Al seleccionar un elemento, la UI llamará a `/api/church/{id}` para obtener el detalle unificado (parroquia o capilla).
# - Para poblar la lista de actos se usa `/api/acts/chapel/search` con `chapel_id`, `page` y `limit`.
#
# Notas de mapeo a BD (basado en db_setup/schema_public.sql):
# - Las parroquias están en la tabla `parish`.
# - Las capillas están en `chapel` y referencian `parish` mediante `parish_id`.
# - La relación entre capilla y evento se guarda en `chapel_event` (vincula `chapel_id` con `event_id`).
# - `event` contiene el catálogo de eventos (Matrimonio, Bautismo, etc.).
# - Mantener consistencia con `BaseResponse` utilizado en otros archivos del proyecto.
