openapi: 3.0.0
info:
  title: Módulo Seguridad - APIs
  description: APIs para la gestión de cuentas de trabajadores (asociaciones) y roles/permisos dentro de una parroquia.
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: Gestión de Cuentas (Trabajadores)
    description: APIs para listar, asociar, gestionar roles y el estado de la cuenta de trabajo de usuarios en la parroquia.
  - name: Gestión de Roles y Permisos
    description: CRUD para roles parroquiales y la gestión de permisos asociados a cada rol.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MessageResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de confirmación de la operación.
      required:
        - message

    # --- Esquemas Gestión de Cuentas ---
    WorkerSummary:
      type: object
      properties:
        association_id:
          type: integer
          description: ID de la asociación (association) del trabajador con la parroquia.
        person_id:
          type: integer
          description: ID de la persona.
        first_names:
          type: string
        paternal_surname:
          type: string
        email:
          type: string
          format: email
        active:
          type: boolean
          description: Estado activo de la asociación (association.active).
      required:
        - association_id
        - person_id
        - first_names
        - paternal_surname
        - email
        - active
    WorkerListResponse:
      type: object
      properties:
        total_records:
          type: integer
        total_pages:
          type: integer
        workers:
          type: array
          items:
            $ref: '#/components/schemas/WorkerSummary'
      required:
        - total_records
        - total_pages
        - workers
    InviteWorkerRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Correo electrónico de la persona a asociar/invitar.
      required:
        - email
    WorkerRole:
      type: object
      properties:
        user_role_id:
          type: integer
          description: ID que se usa para Revocar Rol (user_role).
        role_id:
          type: integer
        role_name:
          type: string
        assignment_date:
          type: string
          format: date
      required:
        - user_role_id
        - role_id
        - role_name
        - assignment_date
    WorkerRoleDetails:
      type: object
      properties:
        association_id:
          type: integer
        first_names:
          type: string
        paternal_surname:
          type: string
        email:
          type: string
          format: email
      required:
        - association_id
        - first_names
        - paternal_surname
        - email
    WorkerRolesResponse:
      type: object
      properties:
        worker_details:
          $ref: '#/components/schemas/WorkerRoleDetails'
        active_roles:
          type: array
          items:
            $ref: '#/components/schemas/WorkerRole'
      required:
        - worker_details
        - active_roles
    AssignRoleRequest:
      type: object
      properties:
        role_id:
          type: integer
          description: ID del rol a asignar.
      required:
        - role_id
    AssignRoleResponse:
      type: object
      properties:
        message:
          type: string
        user_role_id:
          type: integer
        role_name:
          type: string
      required:
        - message
        - user_role_id
        - role_name
    RevokeRoleResponse:
      type: object
      properties:
        message:
          type: string
        user_role_id:
          type: integer
        revocation_date:
          type: string
          format: date
      required:
        - message
        - user_role_id
        - revocation_date
    UpdateAssociationStatusRequest:
      type: object
      properties:
        active:
          type: boolean
          description: true para activar, false para suspender.
      required:
        - active
    UpdateAssociationStatusResponse:
      type: object
      properties:
        message:
          type: string
        association_id:
          type: integer
        active:
          type: boolean
      required:
        - message
        - association_id
        - active
    DeleteAssociationResponse:
      type: object
      properties:
        message:
          type: string
        association_id:
          type: integer
        end_date:
          type: string
          format: date
      required:
        - message
        - association_id
        - end_date

    # --- Esquemas Gestión de Roles ---
    RoleSummary:
      type: object
      properties:
        role_id:
          type: integer
        name:
          type: string
        description:
          type: string
        active:
          type: boolean
      required:
        - role_id
        - name
        - description
        - active
    RoleListResponse:
      type: object
      properties:
        total_records:
          type: integer
        total_pages:
          type: integer
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleSummary'
      required:
        - total_records
        - total_pages
        - roles
    CreateRoleRequest:
      type: object
      properties:
        name:
          type: string
          description: Nombre de Rol (único por parroquia).
        description:
          type: string
      required:
        - name
        - description
    CreateRoleResponse:
      type: object
      properties:
        message:
          type: string
        role_id:
          type: integer
        name:
          type: string
      required:
        - message
        - role_id
        - name
    RoleDetail:
      type: object
      properties:
        role_id:
          type: integer
        parish_id:
          type: integer
        name:
          type: string
        description:
          type: string
        active:
          type: boolean
        created_at:
          type: string
          format: date-time
      required:
        - role_id
        - parish_id
        - name
        - description
        - active
        - created_at
    UpdateRoleRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
        - description
    UpdateRoleStatusRequest:
      type: object
      properties:
        active:
          type: boolean
          description: true para activar, false para desactivar.
      required:
        - active
    UpdateRoleStatusResponse:
      type: object
      properties:
        message:
          type: string
        role_id:
          type: integer
        active:
          type: boolean
      required:
        - message
        - role_id
        - active
    PermissionAssignment:
      type: object
      properties:
        permission_id:
          type: integer
        granted:
          type: boolean
          description: Asignar (true) o Revocar (false).
      required:
        - permission_id
        - granted
    UpdateRolePermissionsRequest:
      type: object
      properties:
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/PermissionAssignment'
      required:
        - permissions
    UpdateRolePermissionsResponse:
      type: object
      properties:
        message:
          type: string
        role_id:
          type: integer
        updated_count:
          type: integer
          description: Número de permisos que fueron asignados o revocados.
      required:
        - message
        - role_id
        - updated_count

paths:
  # --- GESTION DE CUENTAS ---
  /parish/{parishId}/workers:
    get:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Listar Trabajadores (Cuentas activas en la parroquia)
      description: Obtiene la lista paginada de personas asociadas activamente a la parroquia.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: parishId
          schema:
            type: integer
          required: true
          description: ID de la Parroquia que administra.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: true
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          required: true
        - in: query
          name: search
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Listado paginado de trabajadores.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkerListResponse'
    post:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Invitar/Asociar Usuario
      description: Asocia una Persona/Usuario existente (o invita a crear una cuenta) a la Parroquia.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: parishId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteWorkerRequest'
      responses:
        '200':
          description: Usuario asociado o invitación enviada exitosamente.
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                        example: Usuario asociado exitosamente a la parroquia.
                      association_id:
                        type: integer
                    required:
                      - message
                      - association_id
                  - type: object
                    properties:
                      message:
                        type: string
                        example: Usuario no encontrado. Se ha enviado una invitación por correo electrónico para que se registre y se asocie a la parroquia.
                    required:
                      - message

  /parish/associations/{associationId}/roles:
    get:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Ver Roles de Usuario Asociado
      description: Lista todos los roles activos que tiene un trabajador (Association) en la parroquia.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: associationId
          schema:
            type: integer
          required: true
          description: ID de la asociación del trabajador.
      responses:
        '200':
          description: Detalles del trabajador y sus roles activos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkerRolesResponse'
    post:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Asignar Nuevo Rol a Usuario
      description: Asigna un rol específico de la parroquia a un trabajador activo.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: associationId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignRoleRequest'
      responses:
        '201':
          description: Rol asignado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignRoleResponse'

  /parish/user-roles/{userRoleId}:
    patch:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Revocar Rol de Usuario
      description: Finaliza la asignación de un rol a un trabajador (borrado lógico en user_role).
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userRoleId
          schema:
            type: integer
          required: true
          description: ID de la asignación del rol al usuario (user_role_id).
      # Se asume que no necesita body (solamente se actualiza la fecha de revocación internamente)
      responses:
        '200':
          description: Rol revocado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevokeRoleResponse'

  /parish/associations/{associationId}/status:
    patch:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Desactivar/Activar Asociación
      description: Suspende/reestablece temporalmente la cuenta de trabajo del usuario en la parroquia.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: associationId
          schema:
            type: integer
          required: true
          description: ID de la asociación del trabajador.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAssociationStatusRequest'
      responses:
        '200':
          description: Estado de la asociación actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAssociationStatusResponse'

  /parish/associations/{associationId}:
    delete:
      tags:
        - Gestión de Cuentas (Trabajadores)
      summary: Dar de Baja Definitiva (Borrado Lógico)
      description: Finaliza permanentemente la relación laboral del trabajador con la parroquia (actualizando end_date y active=false).
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: associationId
          schema:
            type: integer
          required: true
          description: ID de la asociación del trabajador.
      responses:
        '200':
          description: Asociación laboral finalizada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAssociationResponse'

  # --- GESTION DE ROLES ---
  /parish/{parishId}/roles:
    get:
      tags:
        - Gestión de Roles y Permisos
      summary: Listar Roles (Roles definidos por la Parroquia)
      description: Obtiene la lista paginada de roles definidos por la Parroquia.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: parishId
          schema:
            type: integer
          required: true
          description: ID de la Parroquia.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: true
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          required: true
        - in: query
          name: search
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Listado paginado de roles.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleListResponse'
    post:
      tags:
        - Gestión de Roles y Permisos
      summary: Crear Rol
      description: Crea un nuevo rol dentro del contexto de la parroquia.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: parishId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoleRequest'
      responses:
        '201':
          description: Rol creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoleResponse'

  /parish/roles/{roleId}:
    get:
      tags:
        - Gestión de Roles y Permisos
      summary: Ver/Obtener Detalles del Rol
      description: Obtiene la información completa de un rol específico.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          schema:
            type: integer
          required: true
          description: ID del rol.
      responses:
        '200':
          description: Detalles del rol.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleDetail'
    put:
      tags:
        - Gestión de Roles y Permisos
      summary: Editar Rol
      description: Modifica el nombre o la descripción de un rol existente.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoleRequest'
      responses:
        '200':
          description: Rol actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
    delete:
      tags:
        - Gestión de Roles y Permisos
      summary: Eliminar Rol (Borrado Lógico)
      description: Desactiva/Elimina lógicamente el rol.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          schema:
            type: integer
          required: true
          description: ID del rol.
      responses:
        '200':
          description: Rol desactivado/eliminado lógicamente exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /parish/roles/{roleId}/status:
    patch:
      tags:
        - Gestión de Roles y Permisos
      summary: Desactivar/Activar Rol
      description: Cambia el estado 'active' del rol.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          schema:
            type: integer
          required: true
          description: ID del rol.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoleStatusRequest'
      responses:
        '200':
          description: Estado del rol actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateRoleStatusResponse'

  /parish/roles/{roleId}/permissions:
    put:
      tags:
        - Gestión de Roles y Permisos
      summary: Gestionar Permisos (Asignación Masiva)
      description: Asigna o revoca masivamente los permisos del sistema a un rol específico.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roleId
          schema:
            type: integer
          required: true
          description: ID del rol.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRolePermissionsRequest'
      responses:
        '200':
          description: Permisos del rol actualizados exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateRolePermissionsResponse'