openapi: 3.0.0
info:
  title: Parish Management API
  version: 1.0.0
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        message:
          type: string
          description: "Message to be shown in the frontend"
        data:
          oneOf:
            - type: object
            - type: array
          description: "The main data, can be an object or an array"
        error:
          type: string
          description: "Error string or empty if everything is ok"
        traceback:
          type: string
          description: "Backend error message, returned only during testing phase"
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

paths:
  /api/account/login:
    post:
      summary: User login (Step 1)
      tags:
        - Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  example: "strongpassword"
      responses:
        "200":
          description: Successful login. Returns user info and associated parishes.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "token=...; Path=/; HttpOnly"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          user_name_full:
                            type: string
                            example: "Luis Barboza"
                          associations:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1
                                name:
                                  type: string
                                  example: "La Consolación"

  /api/account/select-parish:
    post:
      summary: Select Parish (Step 2)
      tags:
        - Account
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parishId:
                  type: integer
                  example: 1
      responses:
        "200":
          description: Parish selected. Returns available roles in that parish.
          headers:
            Set-Cookie:
              description: The JWT is updated with the parishId.
              schema:
                type: string
                example: "token=...; Path=/; HttpOnly"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          roles:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 2
                                name:
                                  type: string
                                  example: "Secretario(a)"

  /api/account/select-role:
    post:
      summary: Select Role (Step 3)
      tags:
        - Account
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleId:
                  type: integer
                  example: 2
      responses:
        "200":
          description: Role selected. The session is now fully authenticated.
          headers:
            Set-Cookie:
              description: The JWT is updated with the roleId.
              schema:
                type: string
                example: "token=...; Path=/; HttpOnly"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /api/account/register:
    post:
      summary: User registration
      tags:
        - Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                paternal_surname:
                  type: string
                maternal_surname:
                  type: string
                email:
                  type: string
                  format: email
                type_doc_id:
                  type: integer
                doc_value:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful registration
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        description: "Empty object for this endpoint"

  /api/account/logout:
    post:
      summary: User logout
      tags:
        - Account
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Successful logout. The session cookie is cleared.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          redirect_url:
                            type: string
                            format: url
                            example: "/acceso"