openapi: 3.0.3
info:
  title: API Módulo Usuario - Gestión de Mi Cuenta
  description: |
    API para la gestión de la cuenta del usuario autenticado ("Mi Cuenta").
    
    **Autenticación requerida:** JWT (Cookie)
    
    **Estructura de respuesta estándar:**
    ```json
    {
      "message": "Mensaje descriptivo de la operación",
      "data": {}, 
      "error": "",
      "traceback": ""
    }
    ```
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Servidor de desarrollo

tags:
  - name: Gestionar Mi Cuenta Usuario
    description: Operaciones sobre la cuenta del usuario autenticado

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JWT

  schemas:
    BaseResponse:
      type: object
      properties:
        message:
          type: string
          description: "Mensaje descriptivo de la operación"
        data:
          oneOf:
            - type: object
            - type: array
            - type: string
            - type: integer
          description: "La información principal devuelta por el servicio"
        error:
          type: string
          description: "Mensaje de error, o vacío si todo está OK"
        traceback:
          type: string
          description: "Detalles del error del backend (solo en modo debug)"

    UserAccountDetail:
      type: object
      description: Detalle completo de la cuenta del usuario autenticado.
      properties:
        id:
          type: integer
          example: 5
        first_name:
          type: string
          example: "Juan"
        paternal_last_name:
          type: string
          example: "Pérez"
        maternal_last_name:
          type: string
          example: "García"
        document_id:
          type: string
          example: "1234567"
          description: Número de documento de identidad.
        profile_photo:
          type: string
          example: "usuario.jpg"
          nullable: true
          description: Nombre del archivo de foto de perfil.
        username:
          type: string
          example: "juanperez"
        email:
          type: string
          example: "juan.perez@ejemplo.com"
        active:
          type: boolean
          example: true

security:
  - cookieAuth: []

paths:
# ==============================================================================
# 1. GESTIONAR MI CUENTA USUARIO
# ==============================================================================
  /api/user/account:
    get:
      tags:
        - Gestionar Mi Cuenta Usuario
      summary: 1.1 Obtener información de la cuenta del usuario
      description: |
        Obtiene la información personal y los datos de acceso del usuario autenticado.
        
        **Permisos:** USER_VIEW_ACCOUNT (Se asume que el usuario siempre puede ver su propia cuenta).
      responses:
        '200':
          description: Información obtenida exitosamente
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/UserAccountDetail'
        '401':
          description: No autenticado

  /api/user/account/info:
    patch:
      tags:
        - Gestionar Mi Cuenta Usuario
      summary: 1.2 Actualizar Información Personal del Usuario
      description: |
        Actualiza **parcialmente** la información personal del usuario: nombres, apellidos, documento de identidad y foto de perfil.
        
        **Permisos:** USER_EDIT_ACCOUNT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: "Juan David"
                paternal_last_name:
                  type: string
                  example: "Pérez"
                maternal_last_name:
                  type: string
                  example: "García López"
                document_id:
                  type: string
                  example: "9876543"
                profile_photo:
                  type: string
                  example: "usuario_nuevo.jpg"
                  description: Nombre del archivo de foto de perfil asignado por el servidor.
      responses:
        '200':
          description: Información personal actualizada exitosamente
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 5
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado

  /api/user/account/credentials:
    patch:
      tags:
        - Gestionar Mi Cuenta Usuario
      summary: 1.3 Actualizar Usuario, Correo y/o Contraseña
      description: |
        Actualiza **parcialmente** los datos de acceso: nombre de usuario, email y/o contraseña.
        
        **Permisos:** USER_EDIT_ACCOUNT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "juandperez"
                  description: Nuevo nombre de usuario (opcional)
                email:
                  type: string
                  format: email
                  example: "juan.david.perez@ejemplo.com"
                  description: Nuevo correo electrónico (opcional)
                password:
                  type: string
                  format: password
                  example: "MiClaveSegura2025"
                  description: Nueva contraseña (opcional)
      responses:
        '200':
          description: Credenciales de cuenta actualizadas exitosamente
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 5
        '400':
          description: Datos inválidos
        '401':
          description: No autenticado