openapi: 3.0.3
info:
  title: API de Gestión de Cuenta de Usuario
  version: 1.0.0
paths:
  /api/user/account:
    get:
      tags:
        - Perfil de Usuario
      summary: Obtener la información completa del perfil del usuario autenticado.
      responses:
        '200':
          description: Éxito. Información del perfil obtenida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID del usuario (tabla user).
                      first_names:
                        type: string
                        example: Juan
                        description: Nombres.
                      paternal_surname:
                        type: string
                        example: Pérez
                        description: Apellido paterno.
                      maternal_surname:
                        type: string
                        example: García
                        description: Apellido materno.
                      document:
                        type: string
                        example: 12345678
                        description: Documento de Identidad.
                      profile_photo:
                        type: string
                        example: usuario.jpg
                        description: Foto perfil.
                      username:
                        type: string
                        example: juanperez
                        description: Usuario.
                      email:
                        type: string
                        example: juan.perez@ejemplo.com
                        description: Correo.
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
  
  /api/user/account/info:
    patch:
      tags:
        - Perfil de Usuario
      summary: Actualizar la Información Personal (Nombres, Apellidos, Documento, Foto).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_names:
                  type: string
                  example: Juan Carlos
                paternal_surname:
                  type: string
                  example: Perez Soto
                maternal_surname:
                  type: string
                  example: Garcia Lopez
                document:
                  type: string
                  description: Documento de Identidad (para Person.document).
                  example: 12345678
                profile_photo:
                  type: string
                  example: nueva_foto.png
              required:
                - first_names
                - paternal_surname
                - document
      responses:
        '200':
          description: Éxito. Información personal actualizada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
  
  /api/user/account/credentials:
    patch:
      tags:
        - Perfil de Usuario
      summary: Actualizar Datos de la Cuenta (Usuario, Correo, Nueva Contraseña).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: juancarlosperez
                email:
                  type: string
                  example: juancarlosperez@ejemplo.com
                new_password:
                  type: string
                  nullable: true
                  description: Nueva contraseña (campo 'Nueva contraseña').
                  example: NuevaContra456
                confirm_new_password:
                  type: string
                  nullable: true
                  description: Confirmación de nueva contraseña (campo 'Confirmar contraseña').
                  example: NuevaContra456
              required:
                - username
                - email
      responses:
        '200':
          description: Éxito. Datos de la cuenta actualizados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""