openapi: 3.0.3
info:
  title: API de Gestión de Eventos Generales (Diocesis)
  version: 1.0.0
paths:
  /api/diocese/events/create:
    post:
      tags:
        - Eventos Generales
      summary: Crear un nuevo evento general (tipo base).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Misa Exequial
                  description: Nombre del evento (Event.name).
                description:
                  type: string
                  example: Misa especial para difuntos.
                  description: Descripción del evento (Event.description).
              required:
                - name
      responses:
        '200':
          description: Éxito. Evento general creado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/events/list:
    post:
      tags:
        - Eventos Generales
      summary: Listar eventos generales con paginación.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  example: 1
                  description: Número de página para la paginación.
                limit:
                  type: integer
                  example: 10
                  description: Máximo de registros por página.
              required:
                - page
                - limit
      responses:
        '200':
          description: Éxito. Lista de eventos generales.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID.
                          example: 1
                        name:
                          type: string
                          description: Nombre del evento.
                          example: Evento 1
                        description:
                          type: string
                          description: Descripción.
                          example: Descripción detallada para el Evento 1.
                        active:
                          type: boolean
                          description: Estado (switch).
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 100
                        description: Total de registros disponibles.

  /api/diocese/events/search:
    post:
      tags:
        - Eventos Generales
      summary: Buscar eventos generales por nombre/descripción con paginación.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "bautismo"
                  description: Término de búsqueda (por nombre o descripción).
                page:
                  type: integer
                  example: 1
                  description: Número de página para la paginación.
                limit:
                  type: integer
                  example: 10
                  description: Máximo de registros por página.
              required:
                - query
                - page
                - limit
      responses:
        '200':
          description: Éxito. Resultados de la búsqueda.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID.
                          example: 1
                        name:
                          type: string
                          description: Nombre del evento.
                          example: Bautismo
                        description:
                          type: string
                          description: Descripción.
                          example: Sacramento de iniciación cristiana.
                        active:
                          type: boolean
                          description: Estado (switch).
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 5
                        description: Total de registros que cumplen con la búsqueda.

  /api/diocese/events/{id}:
    get:
      tags:
        - Eventos Generales
      summary: Obtener el detalle de un evento general por ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento.
      responses:
        '200':
          description: Éxito. Detalle del evento.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                        description: ID.
                      name:
                        type: string
                        example: Bautismo
                        description: Nombre.
                      description:
                        type: string
                        example: Sacramento de iniciación cristiana.
                        description: Descripción.
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

    put:
      tags:
        - Eventos Generales
      summary: Actualizar COMPLETAMENTE un evento general por ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Misa Dominical (Nuevo)
                  description: Nuevo nombre del evento.
                description:
                  type: string
                  example: Eucaristía regular del domingo (Descripción actualizada).
                  description: Nueva descripción del evento.
              required:
                - name
      responses:
        '200':
          description: Éxito. Evento actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

    patch:
      tags:
        - Eventos Generales
      summary: Actualizar PARCIALMENTE los datos (Nombre, Descripción) de un evento general.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Misa modificada
                  description: Nombre del evento.
                description:
                  type: string
                  example: Descripción corta modificada.
                  description: Descripción del evento.
      responses:
        '200':
          description: Éxito. Datos actualizados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/events/{id}/status:
    patch:
      tags:
        - Eventos Generales
      summary: Actualizar el estado (switch/active) de un evento general.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: boolean
                  example: false
                  description: Estado de activación (switch).
              required:
                - active
      responses:
        '200':
          description: Éxito. Estado actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/events/{id}/delete:
    delete:
      tags:
        - Eventos Generales
      summary: Eliminar físicamente un evento general por ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento a eliminar.
      responses:
        '200':
          description: Éxito. Evento eliminado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""