openapi: 3.0.3
info:
  title: API de Requisitos Generales Anidados (Diocesis)
  version: 1.0.0
paths:
  # ====================================================================
  # 1. API para Seleccionar el Evento Base (Panel Lateral)
  # ====================================================================
  /api/diocese/events/select:
    get:
      tags:
        - Requisitos Generales
      summary: Listar solo IDs y Nombres de eventos para selección (Panel Lateral).
      responses:
        '200':
          description: Éxito. Lista simple de eventos para selector.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID del evento.
                          example: 1
                        name:
                          type: string
                          description: Nombre del evento.
                          example: Bautismo
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  # ====================================================================
  # 2. APIs de Requisitos Generales (Anidado bajo Evento)
  #    Rutas: /api/diocese/events/{id}/requirements/...
  # ====================================================================

  /api/diocese/events/{id}/requirements/create:
    post:
      tags:
        - Requisitos Generales
      summary: Crear un nuevo requisito base para el Evento {id}.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento al que pertenece el requisito.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Acta de Matrimonio Eclesiástico
                  description: Nombre del requisito (BaseRequirement.name).
                description:
                  type: string
                  example: Copia del acta matrimonial de los padres.
                  description: Descripción del requisito.
              required:
                - name
      responses:
        '200':
          description: Éxito. Requisito base creado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/events/{id}/requirements/list:
    post:
      tags:
        - Requisitos Generales
      summary: Listar requisitos base del Evento {id} con paginación.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento cuyos requisitos se listan.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  example: 1
                  description: Número de página para la paginación.
                limit:
                  type: integer
                  example: 10
                  description: Máximo de registros por página.
              required:
                - page
                - limit
      responses:
        '200':
          description: Éxito. Lista de requisitos base.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID del requisito.
                          example: 1
                        name:
                          type: string
                          description: Nombre del requisito.
                          example: Certificado de Bautismo
                        description:
                          type: string
                          description: Descripción.
                          example: Copia del acta de bautismo.
                        active:
                          type: boolean
                          description: Estado (switch).
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 25
                        description: Total de registros disponibles.

  /api/diocese/events/{id}/requirements/search:
    post:
      tags:
        - Requisitos Generales
      summary: Buscar requisitos base del Evento {id} por nombre/descripción.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento al que pertenece la búsqueda.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "certificado"
                  description: Término de búsqueda (por nombre o descripción).
                page:
                  type: integer
                  example: 1
                  description: Número de página para la paginación.
                limit:
                  type: integer
                  example: 10
                  description: Máximo de registros por página.
              required:
                - query
                - page
                - limit
      responses:
        '200':
          description: Éxito. Resultados de la búsqueda.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID del requisito.
                          example: 1
                        name:
                          type: string
                          description: Nombre del requisito.
                          example: Certificado de Bautismo
                        description:
                          type: string
                          description: Descripción.
                          example: Copia del acta de bautismo.
                        active:
                          type: boolean
                          description: Estado (switch).
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 3
                        description: Total de registros que cumplen con la búsqueda.

  /api/diocese/events/{event_id}/requirements/{id}:
    get:
      tags:
        - Requisitos Generales
      summary: Obtener el detalle de un requisito por ID (Ver).
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento padre.
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
          description: ID del requisito.
      responses:
        '200':
          description: Éxito. Detalle del requisito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 10
                        description: ID.
                      name:
                        type: string
                        example: Ficha de Solicitud de Bautismo
                        description: Nombre.
                      description:
                        type: string
                        example: Formulario de solicitud de sacramento diligenciado.
                        description: Descripción.
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

    put:
      tags:
        - Requisitos Generales
      summary: Actualizar COMPLETAMENTE un requisito por ID (Editar - PUT).
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento padre.
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
          description: ID del requisito a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Formulario de Solicitud (Nuevo)
                  description: Nuevo nombre.
                description:
                  type: string
                  example: Descripción del formulario actualizada.
                  description: Nueva descripción.
              required:
                - name
      responses:
        '200':
          description: Éxito. Requisito actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

    patch:
      tags:
        - Requisitos Generales
      summary: Actualizar PARCIALMENTE los datos (Nombre, Descripción) de un requisito (Editar - PATCH).
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento padre.
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
          description: ID del requisito.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Ficha modificada
                  description: Nombre del requisito.
                description:
                  type: string
                  example: Descripción corta modificada.
                  description: Descripción del requisito.
      responses:
        '200':
          description: Éxito. Datos actualizados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
  
  /api/diocese/events/{event_id}/requirements/{id}/status:
    patch:
      tags:
        - Requisitos Generales
      summary: Actualizar el estado (switch/active) de un requisito.
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento padre.
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
          description: ID del requisito.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: boolean
                  example: false
                  description: Estado de activación (switch).
              required:
                - active
      responses:
        '200':
          description: Éxito. Estado actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/events/{event_id}/requirements/{id}/delete:
    delete:
      tags:
        - Requisitos Generales
      summary: Eliminar físicamente un requisito por ID.
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID del evento padre.
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 10
          description: ID del requisito a eliminar.
      responses:
        '200':
          description: Éxito. Requisito eliminado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""