openapi: 3.0.3
info:
  title: API de Gestión de Parroquias (Diocesis)
  version: 1.0.0
paths:
  /api/diocese/parishes/create:
    post:
      tags:
        - Parroquias
      summary: Crear una nueva parroquia con su usuario administrador asociado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Parroquia San Marcos
                  description: Nombre de la parroquia (Parish.name).
                email:
                  type: string
                  example: sanmarcos@parroquia.com
                  description: Correo del administrador de la parroquia (Person.email).
                username:
                  type: string
                  example: sanmarcos_admin
                  description: Nombre de usuario del administrador (User.username).
                password:
                  type: string
                  example: ClaveSegura123
                  description: Clave inicial del administrador.
              required:
                - name
                - email
                - username
                - password
      responses:
        '200':
          description: Éxito. Parroquia y usuario administrador creados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/parishes/list:
    post:
      tags:
        - Parroquias
      summary: Listar parroquias con paginación.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  example: 1
                  description: Número de página para la paginación.
                limit:
                  type: integer
                  example: 10
                  description: Máximo de registros por página.
              required:
                - page
                - limit
      responses:
        '200':
          description: Éxito. Lista de parroquias.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID.
                          example: 1
                        name:
                          type: string
                          description: Nombre de la parroquia.
                          example: Parroquia 1
                        email:
                          type: string
                          description: Correo del administrador.
                          example: correo1@parroquia.com
                        active:
                          type: boolean
                          description: Estado (switch).
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 100
                        description: Total de registros disponibles.

  /api/diocese/parishes/search:
    post:
      tags:
        - Parroquias
      summary: Buscar parroquias por nombre/correo con paginación.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "marcos"
                  description: Término de búsqueda (por nombre o correo).
                page:
                  type: integer
                  example: 1
                  description: Número de página para la paginación.
                limit:
                  type: integer
                  example: 10
                  description: Máximo de registros por página.
              required:
                - query
                - page
                - limit
      responses:
        '200':
          description: Éxito. Resultados de la búsqueda.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID.
                          example: 1
                        name:
                          type: string
                          description: Nombre de la parroquia.
                          example: Parroquia San Marcos
                        email:
                          type: string
                          description: Correo del administrador.
                          example: sanmarcos@parroquia.com
                        active:
                          type: boolean
                          description: Estado (switch).
                          example: true
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""
                  meta:
                    type: object
                    properties:
                      total_records:
                        type: integer
                        example: 5
                        description: Total de registros que cumplen con la búsqueda.

  /api/diocese/parishes/{id}:
    get:
      tags:
        - Parroquias
      summary: Obtener el detalle de una parroquia por ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID de la parroquia.
      responses:
        '200':
          description: Éxito. Detalle de la parroquia.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                        description: ID de la parroquia.
                      name:
                        type: string
                        example: Parroquia San Marcos
                        description: Nombre.
                      email:
                        type: string
                        example: sanmarcos@parroquia.com
                        description: Correo del administrador.
                      username:
                        type: string
                        example: sanmarcos_admin
                        description: Nombre de usuario del administrador.
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

    put:
      tags:
        - Parroquias
      summary: Actualizar COMPLETAMENTE la parroquia (Nombre, Correo, Usuario).
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID de la parroquia a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Parroquia San Marcos Nuevo
                  description: Nombre de la parroquia.
                email:
                  type: string
                  example: nuevo.marcos@parroquia.com
                  description: Correo del administrador (Person.email).
                username:
                  type: string
                  example: nuevo_marcos_admin
                  description: Nombre de usuario del administrador (User.username).
              required:
                - name
                - email
                - username
      responses:
        '200':
          description: Éxito. Parroquia actualizada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

    patch:
      tags:
        - Parroquias
      summary: Actualizar PARCIALMENTE los datos (Nombre, Correo, Usuario) de la parroquia.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID de la parroquia.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: San Marcos Mod
                  description: Nombre de la parroquia.
                email:
                  type: string
                  example: mod.marcos@parroquia.com
                  description: Correo del administrador (Person.email).
                username:
                  type: string
                  example: mod_marcos_admin
                  description: Nombre de usuario del administrador (User.username).
      responses:
        '200':
          description: Éxito. Datos actualizados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/parishes/{id}/status:
    patch:
      tags:
        - Parroquias
      summary: Actualizar el estado (switch/active) de la parroquia.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID de la parroquia.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: boolean
                  example: false
                  description: Estado de activación (switch).
              required:
                - active
      responses:
        '200':
          description: Éxito. Estado actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""

  /api/diocese/parishes/{id}/delete:
    delete:
      tags:
        - Parroquias
      summary: Eliminar físicamente una parroquia por ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: ID de la parroquia a eliminar.
      responses:
        '200':
          description: Éxito. Parroquia eliminada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: string
                  data:
                    type: object
                    example: {}
                  error:
                    type: string
                    nullable: true
                    example: ""
                  traceback:
                    type: string
                    nullable: true
                    example: ""